FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN apk add --no-cache git
RUN go mod download
RUN cd cmd/api && go build -o /app/api-server main.go
RUN ls -l /app/api-server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/api-server /app/api-server
EXPOSE 8080
CMD ["/app/api-server"] 