FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y git
RUN go mod download
RUN cd cmd/api && go build -o /app/api-server main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/api-server /app/api-server
EXPOSE 8080
CMD ["/app/api-server"] 