version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: blockchain-api:latest
    container_name: blockchain-api
    restart: always
    expose:
      - 8080
    networks:
      - blockchain_net

  nginx:
    image: nginx:alpine
    container_name: blockchain-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - blockchain_net

networks:
  blockchain_net:
    driver: bridge 