server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/containers/*.log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            level: attrs.level
            msg: log

      - labels:
          stream:
          tag:
          level:

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: msg

  - job_name: blockchain-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: blockchain-api
          service: blockchain-sdk-api
          __path__: /var/log/containers/blockchain-api*.log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            level: attrs.level
            msg: log

      - labels:
          stream:
          tag:
          level:

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: msg 